export { TitleConfig, Title } from './components/Title';
export { Feature } from './components/Feature';
export { Super } from './components/Super';
export { SubtitleConfig, Subtitle } from './components/Subtitle';
export { BodyConfig, Body } from './components/Body';
export { MicroConfig, Micro } from './components/Micro';
export { Typography } from './components/Typography';
export { Fonts } from './fonts';
export { default as TypographyConfig } from './typographyConfig';
export { default as brandColor } from './util/brandColor';
